name: dl-guide CI

on: [push, pull_request, workflow_dispatch]

jobs:
  documentation:
    name: Attach Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'false'

      - name: Attach Documentation
        run: cat .github/workflows/README.md >> $GITHUB_STEP_SUMMARY

  build:
    name: Lint and Test dl-guide
    runs-on: ubuntu-latest
    permissions:
       packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: .github/workflows/deps.sh

      - name: Init
        run: bpkg install --dev

      - name: Lint
        run: bpkg run lint
